# Generated by Django 4.2.5 on 2023-12-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
