# Generated by Django 4.2.5 on 2023-12-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reply_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
